# Generated by Django 5.2.5 on 2025-08-20 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        help_text="name of skill. Eg. Software Engineer",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of the skill", null=True
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="years of experience", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("short_bio", models.CharField(blank=True, max_length=255)),
                ("long_bio", models.TextField(null=True)),
                ("country", models.CharField(blank=True, max_length=255)),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="speakers/avatars/"),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers_profile_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_tag",
                    models.ManyToManyField(
                        blank=True,
                        related_name="speakers_profile_skill_tags",
                        to="speakers.speakerskilltag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeakerSocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255, null=True)),
                ("link", models.URLField(max_length=255, null=True)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
