# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("speakers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers_profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="skill_tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="speakers_profile_skill_tags",
                to="speakers.speakerskilltag",
            ),
        ),
        migrations.AddField(
            model_name="speakersociallinks",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="speakers.speakerprofile",
            ),
        ),
    ]
