# Generated by Django 5.2.5 on 2025-11-29 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerExperiences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event", max_length=255),
                ),
                ("event_date", models.DateField(help_text="Date of the event")),
                (
                    "topic",
                    models.CharField(help_text="Topic presented", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of the experience", null=True
                    ),
                ),
                (
                    "presentation_link",
                    models.URLField(
                        help_text="Link to slides of the presentation or talk",
                        null=True,
                    ),
                ),
                (
                    "video_recording_link",
                    models.URLField(
                        help_text="Link to the video recording of the talk", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="experiences",
            field=models.ManyToManyField(
                blank=True,
                related_name="speakers_profile_experiences",
                to="speakers.speakerexperiences",
            ),
        ),
    ]
