# Generated by Django 5.2.5 on 2025-12-05 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("speakers", "0003_speakerexperiences_speakerprofile_experiences"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="events_spoken",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="speakers",
                to="events.event",
            ),
        ),
    ]
