# Generated by Django 5.2.5 on 2025-12-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("speakers", "0003_speakerexperiences_speakerprofile_experiences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakerprofile",
            name="experiences",
        ),
        migrations.AddField(
            model_name="speakerexperiences",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="speakers.speakerprofile",
            ),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="events_spoken",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="speakers",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="event_date",
            field=models.DateField(auto_now=True, help_text="Date of the event"),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="event_name",
            field=models.CharField(
                help_text="Name of the event", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="topic",
            field=models.CharField(
                help_text="Topic presented", max_length=255, null=True
            ),
        ),
    ]
