# Generated by Django 5.2.5 on 2025-12-05 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0003_speakerexperiences_speakerprofile_experiences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakerprofile",
            name="experiences",
        ),
        migrations.AddField(
            model_name="speakerexperiences",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="speakers.speakerprofile",
            ),
        ),
    ]
