# Generated by Django 5.2.5 on 2025-12-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0004_speakerprofile_events_spoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerexperiences",
            name="event_date",
            field=models.DateField(auto_now=True, help_text="Date of the event"),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="event_name",
            field=models.CharField(
                help_text="Name of the event", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="topic",
            field=models.CharField(
                help_text="Topic presented", max_length=255, null=True
            ),
        ),
    ]
