# Generated by Django 5.2.5 on 2025-12-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0004_remove_speakerprofile_experiences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerexperiences",
            name="event_date",
            field=models.DateField(help_text="Date of the event"),
        ),
    ]
