# Generated by Django 5.2.5 on 2025-12-17 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("speakers", "0005_alter_speakerexperiences_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerexperiences",
            name="description",
            field=models.TextField(
                blank=True, help_text="A brief description of the experience", null=True
            ),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="presentation_link",
            field=models.URLField(
                blank=True,
                help_text="Link to slides of the presentation or talk",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="video_recording_link",
            field=models.URLField(
                blank=True,
                help_text="Link to the video recording of the talk",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="events_spoken",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speakers",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="long_bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="speakerskilltag",
            name="description",
            field=models.TextField(
                blank=True, help_text="A brief description of the skill", null=True
            ),
        ),
        migrations.AlterField(
            model_name="speakersociallinks",
            name="link",
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="speakersociallinks",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
