# Generated by Django 5.2.5 on 2026-02-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0006_alter_speakerexperiences_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakerprofile",
            name="skill_tag",
        ),
        migrations.AddField(
            model_name="speakerskilltag",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="skill_tags",
                to="speakers.speakerprofile",
            ),
        ),
    ]
