# Generated by Django 5.2.5 on 2026-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0007_remove_speakerprofile_skill_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
