# Generated by Django 5.2.5 on 2026-02-12 14:21

from django.db import migrations
from django.utils.text import slugify
import uuid

def generate_unique_slugs(apps, schema_editor):
    SpeakerProfile = apps.get_model('speakers', 'SpeakerProfile')
    
    for profile in SpeakerProfile.objects.all():
        base_value = getattr(profile, 'name', 'speaker') 
        if not base_value:
            base_value = 'speaker'
            
        unique_id = uuid.uuid4().hex[:6]
        profile.slug = slugify(f"{base_value}-{unique_id}")
        profile.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0008_speakerprofile_slug"),
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
    ]
