# Generated by Django 5.2.5 on 2026-02-12 14:21

from django.db import migrations
from django.utils.text import slugify
import uuid

def generate_unique_slugs(apps, schema_editor):
    SpeakerProfile = apps.get_model('speakers', 'SpeakerProfile')
    
    for profile in SpeakerProfile.objects.all():
        base_value = getattr(profile, 'user_account__first_name', 'user_account__last_name') 
        if not base_value:
            base_value = profile.user_account.username
            
        profile.slug = slugify(f"{base_value}")
        profile.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0008_speakerprofile_slug"),
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs, migrations.RunPython.noop),
    ]
