# Generated by Django 5.2.5 on 2026-02-23 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0009_auto_20260212_1421"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerprofile",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="SpeakerFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="The user who is following the speaker.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_speakers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        help_text="The speaker profile being followed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("follower", "speaker")},
            },
        ),
    ]
