# Generated by Django 5.2.5 on 2026-05-03 15:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_speaker_deck_upload_enabled"),
        ("speakers", "0012_convert_ids_to_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "link",
                    models.URLField(
                        blank=True, default="", help_text="Optional action URL."
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who receives this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerDeck",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="speaker_decks/")),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of the uploaded file.", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes."),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the presentation.",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="The event this deck is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_decks",
                        to="events.event",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        help_text="The speaker who uploaded this deck.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_decks",
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
