# Generated by Django 5.2.5 on 2026-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "speakers",
            "0015_alter_notification_recipient_alter_speakerdeck_event_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerdeck",
            name="is_deck_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the speaker deck upload feature is enabled for this event.",
            ),
        ),
    ]
