# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the team member", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Job title or role in the company", max_length=100
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        help_text="Brief biography of the team member", max_length=500
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture of the team member",
                        null=True,
                        upload_to="team/avatars/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this team member on the website"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which to display team members"
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_member",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255, null=True)),
                ("link", models.URLField(max_length=255, null=True)),
                (
                    "team_member",
                    models.ForeignKey(
                        help_text="Team member this social link belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="teams.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Social Link",
                "verbose_name_plural": "Team Social Links",
                "db_table": "team_social",
            },
        ),
    ]
