# Generated by Django 5.2.5 on 2026-10-03 20:50

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_teammember_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture of the team member",
                null=True,
                upload_to="team/avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    base.validators.validate_image_size,
                ],
            ),
        ),
    ]
