# Generated by Django 5.2.5 on 2026-05-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_notification_speakerdeck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="The user who receives this notification.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="profiles.speakerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="File size in bytes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original name of the uploaded file.",
                max_length=255,
                null=True,
            ),
        ),
    ]
