# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakers", "0014_alter_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerfollow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerskilltag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakersociallinks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
