# Generated by Django 5.2.5 on 2026-07-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("speakers", "0014_alter_notification_recipient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="The user who receives this notification.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The event this deck is associated with.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_decks",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                help_text="The speaker who uploaded this deck.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_decks",
                to="speakers.speakerprofile",
            ),
        ),
    ]
