# Generated by Django 5.2.5 on 2026-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_notification_created_at_and_more"),
        (
            "profiles",
            "0015_alter_notification_recipient_alter_speakerdeck_event_and_more",
        ),
    ]

    operations = []
