# Generated by Django 5.2.5 on 2026-08-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "speakers",
            "0017_alter_notification_options_alter_speakerdeck_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
