# Generated by Django 5.2.5 on 2026-08-06 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_merge_20260711_1640"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="speakerdeck",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="recipient",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="link",
        ),
        migrations.RemoveField(
            model_name="speakerdeck",
            name="description",
        ),
        migrations.AddField(
            model_name="speakerdeck",
            name="file_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_size",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="event",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_decks",
                to="events.event",
            ),
        ),
    ]
