# Generated by Django 5.2.5 on 2026-08-22 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_eventspeakers_options_alter_country_name"),
        ("speakers", "0016_alter_notification_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who receives this notification.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The event this deck is associated with.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_decks",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_size",
            field=models.PositiveIntegerField(help_text="File size in bytes."),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of the uploaded file.",
                max_length=255,
                null=True,
            ),
        ),
    ]
