# Generated by Django 5.2.5 on 2026-08-24 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_eventspeakers_options_alter_country_name"),
        ("profiles", "0017_rename_tables_to_profiles"),
        ("profiles", "0016_alter_notification_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the organization",
                        null=True,
                    ),
                ),
                (
                    "branding",
                    models.ImageField(
                        blank=True,
                        help_text="Organization branding image",
                        null=True,
                        upload_to="organization_branding/",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for the organization",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Organization website URL", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who receives this notification.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The event this deck is associated with.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_decks",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_size",
            field=models.PositiveIntegerField(help_text="File size in bytes."),
        ),
        migrations.AlterField(
            model_name="speakerdeck",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type of the uploaded file.",
                max_length=255,
                null=True,
            ),
        ),
    ]
