# Generated by Django 5.2.5 on 2026-09-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_organizationcfp_organizationprofile_cfps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="old_status",
            field=models.CharField(
                blank=True, default="pending", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="status",
            field=models.CharField(
                blank=True, default="pending", max_length=50, null=True
            ),
        ),
        migrations.DeleteModel(
            name="SpeakerDeck",
        ),
    ]
