# Generated by Django 5.2.5 on 2026-09-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_organizationprofile_admin_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="cfps",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_cfp",
                to="profiles.organizationcfp",
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="old_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
