# Generated by Django 5.2.5 on 2026-09-12 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_alter_organizationprofile_cfps_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="user_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers_profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
