# Generated by Django 5.2.5 on 2026-09-15 22:46

import secrets

import django.db.models.deletion
from django.db import migrations, models


def backfill_feedback_slugs(apps, schema_editor):
    """Assign a unique opaque feedback token to pre-existing experiences."""
    SpeakerExperiences = apps.get_model("profiles", "SpeakerExperiences")
    for experience in SpeakerExperiences.objects.filter(
        feedback_slug__isnull=True
    ).iterator():
        while True:
            candidate = secrets.token_urlsafe(6)
            exists = SpeakerExperiences.objects.filter(feedback_slug=candidate).exists()
            if not exists:
                experience.feedback_slug = candidate
                experience.save(update_fields=["feedback_slug"])
                break


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_add_country_to_event"),
        ("profiles", "0022_alter_organizationprofile_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerexperiences",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The platform event this experience represents, if listed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speaker_experiences",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="speakerexperiences",
            name="feedback_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether the speaker accepts feedback for this experience.",
            ),
        ),
        migrations.AddField(
            model_name="speakerexperiences",
            name="feedback_slug",
            field=models.SlugField(
                blank=True,
                help_text="Opaque token used in the public feedback (QR) URL.",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_feedback_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="speakerexperiences",
            name="feedback_slug",
            field=models.SlugField(
                blank=True,
                help_text="Opaque token used in the public feedback (QR) URL.",
                max_length=16,
                unique=True,
            ),
        ),
    ]
