# Generated by Django 5.2.5 on 2026-10-03 20:50

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_speakerexperiences_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="branding",
            field=models.ImageField(
                blank=True,
                help_text="Organization branding image",
                null=True,
                upload_to="organization_branding/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    base.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="speakers/avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    base.validators.validate_image_size,
                ],
            ),
        ),
    ]
