# Generated by Django 5.2.5 on 2025-08-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("attendee", "Attendee"),
                    ("organizer", "Organizer"),
                    ("speaker", "Speaker"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
