# Generated by Django 5.2.5 on 2026-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fist_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="Fist name", max_length=255, null=True),
        ),
    ]
