# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_fist_name_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="First name", max_length=255, null=True),
        ),
    ]
