# Generated by Django 5.2.5 on 2025-09-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fist_name",
            field=models.CharField(help_text="Fist name", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nationality",
            field=models.CharField(help_text="Nationality", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(help_text="Last name", max_length=255, null=True),
        ),
    ]
