# Generated by Django 5.2.5 on 2026-02-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_fist_name_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review_talks',
            field=models.BooleanField(default=False, help_text='Grants permission to review talk proposals'),
        ),
    ]
