# Generated by Django 5.2.5 on 2025-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_fist_name_user_nationality_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("attendee", "Attendee"),
                    ("organizer", "Organizer"),
                    ("speaker", "Speaker"),
                    ("admin", "Admin"),
                    ("talk_reviewer", "Talk Reviewer"),
                ],
                max_length=20,
            ),
        ),
    ]
