# Generated by Django 5.2.5 on 2025-10-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_fist_name_user_nationality_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
