# Generated by Django 5.2.5 on 2026-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(help_text="Fist name", max_length=255, null=True),
        ),
    ]
