# Generated by Django 5.2.5 on 2026-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_oauthexchangecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="welcome_email_pending",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
