# Generated by Django 5.2.5 on 2025-11-17 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255, null=True)),
                ("code", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("venue", models.CharField(max_length=255, unique=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("description", models.TextField(null=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_country",
                        to="events.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "event_nickname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "event_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brief description for event cards",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description for event page",
                    ),
                ),
                ("website", models.URLField(blank=True, default="", max_length=255)),
                (
                    "start_date_time",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organizer who created this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_location",
                        to="events.location",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
