# Generated by Django 5.2.5 on 2025-09-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
