# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                help_text="The organizer who created this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_country",
                to="events.country",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="event_location",
                to="events.location",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.tag"
            ),
        ),
    ]
