# Generated by Django 5.2.5 on 2026-03-24 23:38

from django.db import migrations
from django.utils.text import slugify


def create_existing_event_slugs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        event.slug = slugify(event.title)
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_country_updated_at_alter_event_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(create_existing_event_slugs, migrations.RunPython.noop)
    ]
