# Generated by Django 5.2.5 on 2025-10-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_delete_session"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that owns this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("organization__isnull", False)),
                name="event_must_have_organization",
            ),
        ),
    ]
