# Generated by Django 5.2.5 on 2026-03-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20260324_2338"),
        ("organizations", "0002_organization_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                help_text="The organizer who created this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
