# Generated by Django 5.2.5 on 2026-03-25 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_slug_alter_country_code_alter_country_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
