# Generated by Django 5.2.5 on 2026-03-25 23:27

import uuid
from django.db import migrations, models


def pgcrypto_if_postgres(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')


def drop_fk_constraints(apps, schema_editor):
    """Dynamically find and drop ALL FK constraints referencing the tables we're converting to UUID,
    including constraints from other apps (attendees, speakers, speakerrequests, etc.)."""

    if schema_editor.connection.vendor != "postgresql":
        return

    cursor = schema_editor.connection.cursor()
    target_pk_tables = [
        "events_country",
        "events_location",
        "events_event",
        "events_tag",
    ]

    cursor.execute(
        """
        SELECT
            tc.table_name,
            kcu.column_name,
            tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name
          AND tc.table_schema = ccu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND ccu.table_name = ANY(%s);
        """,
        [target_pk_tables],
    )
    fk_constraints = cursor.fetchall()

    for table_name, column_name, constraint_name in fk_constraints:
        cursor.execute(
            f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}";'
        )

    already_handled = {
        ("events_location", "country_id"),
        ("events_event", "location_id"),
        ("events_event_tags", "event_id"),
        ("events_event_tags", "tag_id"),
    }
    converted_fks = []
    for table_name, column_name, constraint_name in fk_constraints:
        if (table_name, column_name) not in already_handled:
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" DROP NOT NULL;'
            )
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" TYPE uuid USING (NULL);'
            )
            converted_fks.append((table_name, column_name, constraint_name))


def convert_columns_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE events_country ALTER COLUMN id DROP IDENTITY IF EXISTS;")
        schema_editor.execute("ALTER TABLE events_location ALTER COLUMN id DROP IDENTITY IF EXISTS;")
        schema_editor.execute("ALTER TABLE events_event ALTER COLUMN id DROP IDENTITY IF EXISTS;")
        schema_editor.execute("ALTER TABLE events_tag ALTER COLUMN id DROP IDENTITY IF EXISTS;")
        schema_editor.execute("ALTER TABLE events_country ALTER COLUMN id TYPE uuid USING (gen_random_uuid());")
        schema_editor.execute("ALTER TABLE events_location ALTER COLUMN id TYPE uuid USING (gen_random_uuid());")
        schema_editor.execute("ALTER TABLE events_event ALTER COLUMN id TYPE uuid USING (gen_random_uuid());")
        schema_editor.execute("ALTER TABLE events_tag ALTER COLUMN id TYPE uuid USING (gen_random_uuid());")
        schema_editor.execute("ALTER TABLE events_location ALTER COLUMN country_id DROP NOT NULL;")
        schema_editor.execute("ALTER TABLE events_location ALTER COLUMN country_id TYPE uuid USING (NULL);")
        schema_editor.execute("ALTER TABLE events_event ALTER COLUMN location_id DROP NOT NULL;")
        schema_editor.execute("ALTER TABLE events_event ALTER COLUMN location_id TYPE uuid USING (NULL);")
        schema_editor.execute("TRUNCATE events_event_tags;")
        schema_editor.execute("ALTER TABLE events_event_tags ALTER COLUMN event_id DROP NOT NULL;")
        schema_editor.execute("ALTER TABLE events_event_tags ALTER COLUMN event_id TYPE uuid USING (NULL);")
        schema_editor.execute("ALTER TABLE events_event_tags ALTER COLUMN tag_id DROP NOT NULL;")
        schema_editor.execute("ALTER TABLE events_event_tags ALTER COLUMN tag_id TYPE uuid USING (NULL);")


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_slug_alter_country_code_alter_country_name_and_more"),
    ]

    operations = [
        migrations.RunPython(pgcrypto_if_postgres, migrations.RunPython.noop),
        migrations.RunPython(drop_fk_constraints, migrations.RunPython.noop),
        migrations.RunPython(convert_columns_to_uuid, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="country",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="event",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="tag",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
