# Generated by Django 5.2.5 on 2026-03-25 23:27

import uuid
from django.db import migrations, models


def drop_fk_constraints(apps, schema_editor):
    """Dynamically find and drop ALL FK constraints referencing the tables we're converting to UUID,
    including constraints from other apps (attendees, speakers, speakerrequests, etc.)."""
    
    cursor = schema_editor.connection.cursor()
    target_pk_tables = ["events_country", "events_location", "events_event", "events_tag"]

    cursor.execute(
        """
        SELECT
            tc.table_name,
            kcu.column_name,
            tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name
          AND tc.table_schema = ccu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND ccu.table_name = ANY(%s);
        """,
        [target_pk_tables],
    )
    fk_constraints = cursor.fetchall()

    for table_name, column_name, constraint_name in fk_constraints:
        cursor.execute(
            f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}";'
        )

    already_handled = {
        ("events_location", "country_id"),
        ("events_event", "location_id"),
        ("events_event_tags", "event_id"),
        ("events_event_tags", "tag_id"),
    }
    converted_fks = []
    for table_name, column_name, constraint_name in fk_constraints:
        if (table_name, column_name) not in already_handled:
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" DROP NOT NULL;'
            )
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" TYPE uuid USING (NULL);'
            )
            converted_fks.append((table_name, column_name, constraint_name))




class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_slug_alter_country_code_alter_country_name_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS "pgcrypto";',
        ),
        migrations.RunPython(drop_fk_constraints, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE events_country ALTER COLUMN id DROP IDENTITY IF EXISTS;",
                "ALTER TABLE events_location ALTER COLUMN id DROP IDENTITY IF EXISTS;",
                "ALTER TABLE events_event ALTER COLUMN id DROP IDENTITY IF EXISTS;",
                "ALTER TABLE events_tag ALTER COLUMN id DROP IDENTITY IF EXISTS;",
                "ALTER TABLE events_country ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
                "ALTER TABLE events_location ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
                "ALTER TABLE events_event ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
                "ALTER TABLE events_tag ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
                "ALTER TABLE events_location ALTER COLUMN country_id DROP NOT NULL;",
                "ALTER TABLE events_location ALTER COLUMN country_id TYPE uuid USING (NULL);",
                "ALTER TABLE events_event ALTER COLUMN location_id DROP NOT NULL;",
                "ALTER TABLE events_event ALTER COLUMN location_id TYPE uuid USING (NULL);",
                "TRUNCATE events_event_tags;",
                "ALTER TABLE events_event_tags ALTER COLUMN event_id DROP NOT NULL;",
                "ALTER TABLE events_event_tags ALTER COLUMN event_id TYPE uuid USING (NULL);",
                "ALTER TABLE events_event_tags ALTER COLUMN tag_id DROP NOT NULL;",
                "ALTER TABLE events_event_tags ALTER COLUMN tag_id TYPE uuid USING (NULL);",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="country",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="event",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="tag",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
