# Generated by Django 5.2.5 on 2026-03-25 23:27
"""Convert events primary keys to UUID, preserving inbound foreign keys."""

import uuid

from django.db import migrations, models

from base.db_migration_utils import FkConstraintSnapshot, enable_pgcrypto

snapshot = FkConstraintSnapshot()

TARGET_PK_TABLES = [
    "events_country",
    "events_location",
    "events_event",
    "events_tag",
]

# Columns converted inside convert_own_columns_to_uuid below.
already_handled = {
    ("events_location", "country_id"),
    ("events_event", "location_id"),
    ("events_event_tags", "event_id"),
    ("events_event_tags", "tag_id"),
}

OWN_CONVERSION_STATEMENTS = [
    "ALTER TABLE events_country ALTER COLUMN id DROP IDENTITY IF EXISTS;",
    "ALTER TABLE events_location ALTER COLUMN id DROP IDENTITY IF EXISTS;",
    "ALTER TABLE events_event ALTER COLUMN id DROP IDENTITY IF EXISTS;",
    "ALTER TABLE events_tag ALTER COLUMN id DROP IDENTITY IF EXISTS;",
    "ALTER TABLE events_country ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
    "ALTER TABLE events_location ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
    "ALTER TABLE events_event ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
    "ALTER TABLE events_tag ALTER COLUMN id TYPE uuid USING (gen_random_uuid());",
    "ALTER TABLE events_location ALTER COLUMN country_id DROP NOT NULL;",
    "ALTER TABLE events_location ALTER COLUMN country_id TYPE uuid USING (NULL);",
    "ALTER TABLE events_event ALTER COLUMN location_id DROP NOT NULL;",
    "ALTER TABLE events_event ALTER COLUMN location_id TYPE uuid USING (NULL);",
    "TRUNCATE events_event_tags;",
    "ALTER TABLE events_event_tags ALTER COLUMN event_id DROP NOT NULL;",
    "ALTER TABLE events_event_tags ALTER COLUMN event_id TYPE uuid USING (NULL);",
    "ALTER TABLE events_event_tags ALTER COLUMN tag_id DROP NOT NULL;",
    "ALTER TABLE events_event_tags ALTER COLUMN tag_id TYPE uuid USING (NULL);",
]


def drop_inbound_fks(apps, schema_editor):
    """Drop FK constraints referencing the converted tables, capturing definitions."""
    snapshot.drop(schema_editor, TARGET_PK_TABLES, already_handled)


def convert_own_columns_to_uuid(apps, schema_editor):
    """Convert the app's own PK and FK columns to uuid."""
    snapshot.convert_targets(schema_editor, OWN_CONVERSION_STATEMENTS)


def restore_inbound_fks(apps, schema_editor):
    """Re-add every FK constraint dropped for the conversion."""
    snapshot.restore(schema_editor)


class Migration(migrations.Migration):
    """Convert events PKs to UUID while preserving inbound foreign keys."""
    dependencies = [
        ("events", "0004_event_slug_alter_country_code_alter_country_name_and_more"),
    ]

    operations = [
        migrations.RunPython(enable_pgcrypto, migrations.RunPython.noop),
        migrations.RunPython(drop_inbound_fks, migrations.RunPython.noop),
        migrations.RunPython(convert_own_columns_to_uuid, migrations.RunPython.noop),
        # State-only: physical conversion happened in convert_own_columns_to_uuid.
        # Schema-editor-emitted casts would break cross-app FK reconciliation.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="country",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="event",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="location",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="tag",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ]
        ),
        migrations.RunPython(restore_inbound_fks, migrations.RunPython.noop),
    ]
