# Generated by Django 5.2.5 on 2026-03-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_country_id_alter_event_id_alter_location_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="venue",
            field=models.CharField(max_length=255),
        ),
    ]
