# Generated by Django 5.2.5 on 2026-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accepts_cfp",
            field=models.BooleanField(
                default=False,
                help_text="Does this event accept Call for Papers submissions?",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_deadline",
            field=models.DateTimeField(
                blank=True, help_text="When CFP submissions close.", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What the organizers are looking for — shown to speakers on the CFP page.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_open",
            field=models.BooleanField(
                default=False, help_text="Is the CFP currently open for submissions?"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_open_date",
            field=models.DateTimeField(
                blank=True, help_text="When CFP submissions open.", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_speaker_notification_date",
            field=models.DateField(
                blank=True,
                help_text="When speakers will be notified of the outcome.",
                null=True,
            ),
        ),
    ]
