# Generated by Django 5.2.5 on 2026-05-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_cfp_fields_to_event"),
        ("events", "0008_eventspeakers"),
    ]

    operations = []
