# Generated by Django 5.2.5 on 2026-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_cfp_fields_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="speaker_deck_upload_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, accepted speakers can upload their presentation materials.",
            ),
        ),
    ]
