# Generated by Django 5.2.5 on 2026-07-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("events", "0009_merge_0008_add_cfp_fields_to_event_0008_eventspeakers"),
    ]

    operations = []
