# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_event_slug_alter_event_title_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
