# Generated by Django 5.2.5 on 2026-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_country_created_at_alter_event_created_at_and_more"),
        ("events", "0010_alter_event_is_active"),
        ("events", "0011_remove_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
