# Generated by Django 5.2.5 on 2026-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_country_created_at_alter_event_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
