# Generated by Django 5.2.5 on 2026-08-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_eventspeakers"),
        ("events", "0010_alter_event_is_active"),
        ("events", "0011_alter_event_slug_alter_event_title_alter_tag_name_and_more"),
    ]

    operations = []
