# Generated by Django 5.2.5 on 2026-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_add_event_cfp_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventspeakers",
            options={
                "verbose_name": "Event Speaker",
                "verbose_name_plural": "Event Speakers",
            },
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
