# Generated by Django 5.2.5 on 2026-08-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_eventspeakers_options_alter_country_name"),
        ("events", "0012_add_event_cfp_link"),
    ]

    operations = []
