# Generated by Django 5.2.5 on 2026-08-22 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_event_cfp_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventspeakers',
            options={'verbose_name': 'Event Speaker', 'verbose_name_plural': 'Event Speakers'},
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_url',
            field=models.URLField(blank=True, default='', help_text='External Call for Papers URL, if the event has one.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The user who submitted this event for listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, help_text='Official event website URL.', max_length=255, null=True),
        ),
    ]
