# Generated by Django 5.2.5 on 2026-08-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_eventspeakers_options_alter_country_name"),
        ("events", "0014_require_event_website"),
    ]

    operations = []
