# Generated by Django 5.2.5 on 2026-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_require_event_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="eventspeakers",
            options={
                "verbose_name": "Event Speaker",
                "verbose_name_plural": "Event Speakers",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="cfp_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External Call for Papers URL, if the event has one.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
