# Generated by Django 5.2.5 on 2026-08-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_merge_20260823_2048"),
        ("events", "0015_event_cfp_url_and_meta"),
    ]

    operations = []
