# Generated by Django 5.2.5 on 2026-09-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_merge_20260831_0153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.RemoveField(
            model_name="eventspeakers",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventspeakers",
            name="speaker",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="event",
            name="accepts_cfp",
        ),
        migrations.RemoveField(
            model_name="event",
            name="cfp_description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="cfp_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="speaker_deck_upload_enabled",
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="Event title", max_length=255, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="EventSpeakers",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
