# Generated by Django 5.2.5 on 2026-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_remove_location_country_remove_eventspeakers_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Country where the event takes place.",
                max_length=100,
                null=True,
            ),
        ),
    ]
