# Generated by Django 5.2.5 on 2026-10-03 20:50

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_add_country_to_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    base.validators.validate_image_size,
                ],
                verbose_name="image",
            ),
        ),
    ]
