# Generated by Django 5.2.5 on 2026-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0019_alter_event_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_free",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether attendees can attend without paying. Null means the ticket status has not been specified.",
                null=True,
            ),
        ),
    ]
