# Generated by Django 5.2.5 on 2026-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfps", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cfpsubmission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="duration",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                ],
                help_text="Expected talk duration in minutes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="is_first_time_speaker",
            field=models.BooleanField(
                default=False,
                help_text="Is this your first time speaking at a conference?",
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="language",
            field=models.CharField(
                blank=True,
                default="English",
                help_text="Language the talk will be delivered in.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="notes_for_organizers",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Private notes only visible to organizers.",
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="outline",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Private structured outline of your talk (only visible to organizers).",
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="recording_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a recording of this talk at a previous event.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="slides_url",
            field=models.URLField(
                blank=True,
                help_text="Link to draft slides or a previous version.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="title",
            field=models.CharField(
                default="", help_text="Title of your talk.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="cfpsubmission",
            name="travel_support_needed",
            field=models.BooleanField(
                default=False, help_text="Do you need travel or accommodation support?"
            ),
        ),
    ]
