# Generated by Django 5.2.5 on 2026-07-19 23:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfps", "0002_add_cfp_fields_allow_multiple"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CFPReview",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1 (weak) – 5 (excellent)",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfp_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="cfps.cfpsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "CFP Review",
                "verbose_name_plural": "CFP Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("submission", "reviewer")},
            },
        ),
    ]
