# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfps', '0002_add_cfp_fields_allow_multiple'),
        ('cfps', '0003_alter_cfpsubmission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfpsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
