# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfps", "0002_add_cfp_fields_allow_multiple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfpsubmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
