# Generated by Django 5.2.5 on 2026-05-21 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0008_add_cfp_fields_to_event"),
        ("eventsessions", "0002_alter_sessionspeaker_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_schedules",
                        to="events.event",
                    ),
                ),
                (
                    "session",
                    models.ManyToManyField(
                        related_name="event_schedules", to="eventsessions.session"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Schedule",
                "verbose_name_plural": "Event Schedules",
                "db_table": "event_schedules",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["event", "id"], name="event_sched_event_i_b84e44_idx"
                    )
                ],
            },
        ),
    ]
