# Generated by Django 5.2.5 on 2026-05-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventschedules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventschedule",
            old_name="session",
            new_name="sessions",
        ),
    ]
