# Generated by Django 5.2.5 on 2026-07-04 16:56

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_event_schedules(apps, schema_editor):
    """Remove duplicate EventSchedule rows for the same event, keeping only the most recent."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE;")
    EventSchedule = apps.get_model("eventschedules", "EventSchedule")
    seen_events = set()
    to_delete = []
    for es in EventSchedule.objects.all().order_by("-created_at"):
        if es.event_id in seen_events:
            to_delete.append(es.pk)
        else:
            seen_events.add(es.event_id)
    EventSchedule.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("eventschedules", "0002_rename_session_eventschedule_sessions"),
    ]

    operations = [
        migrations.RunPython(deduplicate_event_schedules, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="eventschedule",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_schedules",
                to="events.event",
            ),
        ),
    ]
