# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventschedules", "0002_rename_session_eventschedule_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
