# Generated by Django 5.2.5 on 2026-07-22 16:16
# Generated by Django 5.2.5 on 2026-07-19 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_is_active'),
        ('eventschedules', '0003_alter_eventschedule_event'),
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("eventschedules", "0003_alter_eventschedule_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule', to='events.event'),
            model_name="eventschedule",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_schedule",
                to="events.event",
            ),
        ),
    ]
