# Generated by Django 5.2.5 on 2026-07-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_is_active"),
        ("eventschedules", "0003_alter_eventschedule_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventschedule",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_schedule",
                to="events.event",
            ),
        ),
    ]
