# Generated by Django 5.2.5 on 2026-04-16 22:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0007_alter_event_location"),
        ("speakers", "0011_alter_speakerexperiences_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CFPSubmission",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "talk_type",
                    models.CharField(
                        choices=[
                            ("short", "Short Talk"),
                            ("demo", "Demo"),
                            ("long", "Long Talk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all", "All Levels"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai and ml", "Artificial Intelligence & Machine Learning"),
                            ("cloud and devops", "Cloud Computing & DevOps"),
                            ("cybersecurity", "Cybersecurity & Privacy"),
                            ("data science", "Data Science & Analytics"),
                            ("frontend", "Frontend Development"),
                            ("backend", "Backend Development"),
                            ("fullstack", "Full-Stack Development"),
                            ("mobile", "Mobile Development"),
                            ("web", "Web Development"),
                            ("devtools", "DevTools & Productivity"),
                            ("programming languages", "Programming Languages"),
                            ("software architecture", "Software Architecture & Design"),
                            ("database", "Database Technologies"),
                            ("blockchain", "Blockchain & Web3"),
                            ("iot", "Internet of Things (IoT)"),
                            ("quantum computing", "Quantum Computing"),
                            ("open source", "Open Source & Community"),
                            ("agile", "Agile & Project Management"),
                            ("emerging technologies", "Emerging Technologies"),
                            ("tech ethics", "Tech Ethics & Governance"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "elevator_pitch",
                    models.CharField(
                        help_text="A short summary of your talk (max 300 characters).",
                        max_length=300,
                    ),
                ),
                (
                    "abstract",
                    models.TextField(help_text="Full description of your talk."),
                ),
                (
                    "other_speakers_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Names/emails of co-presenters not yet on SpeakWise.",
                    ),
                ),
                ("other_comments", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "co_speakers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Registered co-presenters.",
                        related_name="co_speaker_cfp_submissions",
                        to="speakers.speakerprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfp_submissions",
                        to="events.event",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfp_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CFP Submission",
                "verbose_name_plural": "CFP Submissions",
                "ordering": ["-created_at"],
                "unique_together": {("event", "submitter")},
            },
        ),
    ]
