# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendees", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("overall_rating", models.IntegerField()),
                ("engagement", models.IntegerField()),
                ("clarity", models.IntegerField()),
                ("content_depth", models.IntegerField()),
                ("speaker_knowledge", models.IntegerField()),
                ("practical_relevance", models.IntegerField()),
                ("comments", models.TextField(blank=True, max_length=2000, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendee_feedbacks",
                        to="attendees.attendeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "db_table": "feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
