# Generated by Django 5.2.5 on 2025-11-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedbacks", "0001_initial"),
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_feedbacks",
                to="talks.session",
            ),
        ),
    ]
