# Generated by Django 5.2.5 on 2025-11-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
        ("speakers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="attendee",
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_attendee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="speaker_feedback",
                to="speakers.speakerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="clarity",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="content_depth",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="engagement",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="overall_rating",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="practical_relevance",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="speaker_knowledge",
            field=models.IntegerField(
                error_messages={"error": "value should be an integer of value 1-10"}
            ),
        ),
    ]
