# Generated by Django 5.2.5 on 2025-12-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_remove_feedback_attendee_feedback_is_attendee_and_more"),
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_feedback",
                to="talks.session",
            ),
        ),
    ]
