# Generated by Django 5.2.5 on 2026-02-25 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_remove_feedback_attendee_feedback_is_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='clarity',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content_depth',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='engagement',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_rating',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='practical_relevance',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='speaker_knowledge',
            field=models.IntegerField(error_messages={'error': 'value should be an integer of value 1-10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
