# Generated by Django 5.2.5 on 2026-05-05 21:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_speaker_deck_upload_enabled'),
        ('feedbacks', '0004_convert_ids_to_uuid'),
        ('speakers', '0013_notification_speakerdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_feedback', to='events.event'),
        ),
        migrations.CreateModel(
            name='SpeakerFeedbackSettings',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_feedback_settings', to='events.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_settings', to='speakers.speakerprofile')),
            ],
            options={
                'db_table': 'speaker_feedback_settings',
                'unique_together': {('speaker', 'event')},
            },
        ),
    ]
