# Generated by Django 5.2.5 on 2026-07-17 00:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("feedbacks", "0004_convert_ids_to_uuid"),
        (
            "speakers",
            "0015_alter_notification_recipient_alter_speakerdeck_event_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The event the feedback was given at.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="events.event",
            ),
        ),
        migrations.CreateModel(
            name="EventFeedbackPreference",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_feedback_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the speaker accepts feedback for this event.",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_feedback_preferences",
                        to="events.event",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_feedback_preferences",
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Feedback Preference",
                "verbose_name_plural": "Event Feedback Preferences",
                "db_table": "event_feedback_preferences",
                "ordering": ["-created_at"],
                "unique_together": {("speaker", "event")},
            },
        ),
    ]
