# Generated by Django 5.2.5 on 2026-08-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0005_feedback_event_eventfeedbackpreference"),
        ("profiles", "0017_rename_tables_to_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeedbackpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speaker_feedback",
                to="profiles.speakerprofile",
            ),
        ),
    ]
