# Generated by Django 5.2.5 on 2026-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0005_feedback_event_eventfeedbackpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeedbackpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
