# Generated by Django 5.2.5 on 2026-09-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0006_alter_eventfeedbackpreference_created_at_and_more"),
        ("profiles", "0022_alter_organizationprofile_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                help_text="The presentation the feedback was given for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to="profiles.speakerexperiences",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional public name of the person giving feedback.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="submitter_ip_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Salted hash of the submitter's IP used for rate limiting.",
                max_length=64,
            ),
        ),
    ]
