# Generated by Django 5.2.5 on 2026-09-15 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0007_feedback_experience_feedback_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="event",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="is_attendee",
        ),
        migrations.DeleteModel(
            name="EventFeedbackPreference",
        ),
    ]
