# Generated by Django 5.2.5 on 2025-11-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="members",
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MEMBER", "Member"),
                    ("ORGANIZER", "Organizer"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
    ]
