# Generated by Django 5.2.5 on 2026-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="members",
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MEMBER", "Member"),
                    ("ORGANIZER", "Organizer"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
