# Generated by Django 5.2.5 on 2025-11-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="members",
        ),
    ]
