# Generated by Django 5.2.5 on 2026-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
