<<<<<<< HEAD
# Generated by Django 5.1 on 2026-03-21 09:58
=======
# Generated by Django 5.2.5 on 2026-05-09 20:28
>>>>>>> ee971b9 (fix: recreate feedback migration with correct dependencies and add organization status migration)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_merge_0002_organization_slug_0002_organization_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
