# Generated by Django 5.2.5 on 2026-05-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_organization_status"),
        ("organizations", "0004_fix_cascade_on_delete"),
    ]

    operations = []
