# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_merge_20260509_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('ORGANIZER', 'Organizer')], db_index=True, default='MEMBER', max_length=20),
        ),
    ]
