# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_merge_20260509_1654"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
