# Generated by Django 5.2.5

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blog_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog_images/"
                    ),
                ),
                ("blog_title", models.CharField(max_length=255)),
                (
                    "blog_short_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short summary shown on cards.",
                        max_length=255,
                    ),
                ),
                (
                    "blog_full_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        help_text="Full blog content. Rich text (HTML) supported.",
                    ),
                ),
                (
                    "blog_created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created the blog post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("blog_published_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-blog_published_date", "-created_at"],
            },
        ),
    ]
