# Generated by Django 5.2.5 on 2026-08-05 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-published_date", "-created_at"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_created_by",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_full_description",
            new_name="full_description",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_published_date",
            new_name="published_date",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_short_description",
            new_name="short_description",
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="blog_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blog",
            unique_together={("created_by", "title")},
        ),
    ]
