# Generated by Django 5.2.5 on 2026-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfps", "0003_add_cfp_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfpreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
