# Generated by Django 5.2.5 on 2025-10-02 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_delete_session"),
        ("organizers", "0002_alter_organizerprofile_user_account"),
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="events.event",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="organizers.organizerprofile",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
