# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("speakerrequests", "0001_initial"),
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerrequest",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="speakers.speakerprofile",
            ),
        ),
    ]
