# Generated by Django 5.2.5 on 2025-10-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
