# Generated by Django 5.2.5 on 2026-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakerrequests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
