# Generated by Django 5.2.5 on 2025-11-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_remove_organization_members_and_more"),
        ("speakerrequests", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerrequest",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="organizations.organization",
            ),
        ),
    ]
