# Generated by Django 5.2.5 on 2026-03-06 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("speakerrequests", "0004_emailrequests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailRequests",
            new_name="SpeakerEmailRequests",
        ),
    ]
