# Generated by Django 5.2.5 on 2026-03-02 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0004_emailrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailrequests",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f6e4aa72-6ba2-4709-be09-bbfafb607514"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
