# Generated by Django 5.2.5 on 2026-03-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_country_updated_at_alter_event_updated_at_and_more"),
        ("organizations", "0001_initial"),
        ("speakerrequests", "0005_rename_emailrequests_speakeremailrequests"),
        ("speakers", "0011_alter_speakerexperiences_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speakerrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="speakerrequest",
            unique_together={("organizer", "speaker", "event")},
        ),
    ]
