# Generated by Django 5.2.5 on 2026-05-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_cfp_fields_to_event"),
        ("organizations", "0004_fix_cascade_on_delete"),
        ("speakerrequests", "0007_convert_ids_to_uuid"),
        ("speakers", "0012_convert_ids_to_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerrequest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="speakers.speakerprofile",
            ),
        ),
    ]
