# Generated by Django 5.2.5 on 2026-07-04 09:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_speaker_deck_upload_enabled"),
        ("speakerrequests", "0008_fix_cascade_on_delete"),
        ("speakers", "0014_alter_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerrequest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="speakers.speakerprofile",
            ),
        ),
    ]
