# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0008_fix_cascade_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakeremailrequests",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
