# Generated by Django 5.2.5 on 2026-06-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_country_created_at_alter_event_created_at_and_more"),
        ("organizations", "0006_alter_organization_created_at_and_more"),
        ("speakerrequests", "0009_alter_speakeremailrequests_created_at_and_more"),
        ("speakers", "0015_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speakerrequest",
            old_name="organizer",
            new_name="organization",
        ),
        migrations.AlterUniqueTogether(
            name="speakerrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="accommodation_covered",
            field=models.BooleanField(
                default=False,
                help_text="Whether accommodation is covered by the organizer",
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="notes",
            field=models.TextField(
                help_text="Internal organizer notes, not visible to the speaker",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="proposed_duration",
            field=models.PositiveIntegerField(
                help_text="Proposed duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="proposed_session_type",
            field=models.CharField(
                choices=[("online", "Online"), ("in_person", "In Person")],
                default="in_person",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="proposed_topic",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_made",
                to="speakers.speakerprofile",
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="responded_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="response_deadline",
            field=models.DateTimeField(
                help_text="Deadline for the speaker to respond to the request",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="response_message",
            field=models.TextField(
                help_text="Speaker's response or reason for declining", null=True
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="speaker_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Honorarium or fee offered to the speaker, if any",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="speakerrequest",
            name="travel_covered",
            field=models.BooleanField(
                default=False,
                help_text="Whether travel expenses are covered by the organizer",
            ),
        ),
        migrations.AlterField(
            model_name="speakeremailrequests",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("is_expired", "Is Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=225,
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_received",
                to="speakers.speakerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="speakerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("is_expired", "Is Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speakerrequest",
            unique_together={("organization", "speaker", "event")},
        ),
    ]
