# Generated by Django 5.2.5 on 2026-07-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0009_alter_speakeremailrequests_request_from_and_more"),
        (
            "speakerrequests",
            "0009_alter_speakerrequest_event_alter_speakerrequest_id_and_more",
        ),
    ]

    operations = []
