# Generated by Django 5.2.5 on 2026-06-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakerrequests', '0010_rename_organizer_speakerrequest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('is_expired', 'Is Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
