# Generated by Django 5.2.5 on 2026-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_event_organizer"),
        (
            "speakerrequests",
            "0010_alter_speakeremailrequests_request_from_and_more",
        ),
        (
            "speakerrequests",
            "0010_rename_organizer_speakerrequest_organization_and_more",
        ),
        ("profiles", "0016_alter_notification_is_read"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="speakerrequest",
            unique_together={("speaker", "event")},
        ),
    ]
