# Generated by Django 5.2.5 on 2026-07-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0010_merge_20260705_1154"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakeremailrequests",
            name="request_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="speaker_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
