# Generated by Django 5.2.5 on 2026-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "speakerrequests",
            "0009_alter_speakerrequest_event_alter_speakerrequest_id_and_more",
        ),
        ("speakerrequests", "0011_alter_speakerrequest_status"),
    ]

    operations = []
