# Generated by Django 5.2.5 on 2026-07-11 16:40

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakerrequests", "0012_merge_20260711_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerrequest",
            name="speaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_received",
                to="profiles.speakerprofile",
            ),
        ),
    ]
