# Generated by Django 5.2.5 on 2026-05-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventsessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionspeaker",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_speakers",
                to="eventsessions.session",
            ),
        ),
        migrations.AlterField(
            model_name="sessionsponsor",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_sponsors",
                to="eventsessions.session",
            ),
        ),
        migrations.AlterField(
            model_name="sessionsponsor",
            name="sponsor",
            field=models.CharField(max_length=255),
        ),
    ]
