# Generated by Django 5.2.5 on 2026-05-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_add_cfp_fields_to_event"),
        ("eventsessions", "0002_alter_sessionspeaker_session_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ("-start_date_time",),
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.RenameField(
            model_name="session",
            old_name="end_time",
            new_name="end_date_time",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="start_time",
            new_name="start_date_time",
        ),
        migrations.AlterField(
            model_name="session",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_sessions",
                to="events.event",
            ),
        ),
    ]
