# Generated by Django 5.2.5 on 2026-05-24 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_merge_0008_add_cfp_fields_to_event_0008_eventspeakers"),
        ("eventsessions", "0002_alter_sessionspeaker_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_sessions",
                to="events.event",
            ),
        ),
    ]
