# Generated by Django 5.2.5 on 2026-05-21 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventsessions", "0003_alter_session_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="abstract",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="session",
            name="end_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="session",
            name="max_attendees",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sessionsponsor",
            name="sponsor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sessionvenue",
            name="capacity",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="sessionvenue",
            name="location_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="track",
            name="color",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
