# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsessions', '0004_alter_session_abstract_alter_session_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
