# Generated by Django 5.2.5 on 2026-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventsessions",
            "0004_alter_session_abstract_alter_session_end_date_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sessionspeaker",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sessionsponsor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sessionvenue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
