# Generated by Django 5.2.5 on 2026-07-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventsessions", "0003_alter_session_event"),
        (
            "eventsessions",
            "0004_alter_session_abstract_alter_session_end_date_time_and_more",
        ),
    ]

    operations = []
