# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai and ml", "Artificial Intelligence & Machine Learning"),
                            ("cloud and devops", "Cloud Computing & DevOps"),
                            ("cybersecurity", "Cybersecurity & Privacy"),
                            ("data science", "Data Science & Analytics"),
                            ("frontend", "Frontend Development"),
                            ("backend", "Backend Development"),
                            ("fullstack", "Full-Stack Development"),
                            ("mobile", "Mobile Development"),
                            ("web", "Web Development"),
                            ("devtools", "DevTools & Productivity"),
                            ("programming languages", "Programming Languages"),
                            ("software architecture", "Software Architecture & Design"),
                            ("database", "Database Technologies"),
                            ("blockchain", "Blockchain & Web3"),
                            ("iot", "Internet of Things (IoT)"),
                            ("quantum computing", "Quantum Computing"),
                            ("open source", "Open Source & Community"),
                            ("agile", "Agile & Project Management"),
                            ("emerging technologies", "Emerging Technologies"),
                            ("tech ethics", "Tech Ethics & Governance"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "presentation_files",
                    models.FileField(null=True, upload_to="presentation_files"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_event",
                        to="events.event",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_talks",
                        to="speakers.speakerprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        help_text="session type. eg. Keynote, lightning talk. etc",
                        max_length=255,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(help_text="session duration in minutes"),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_sessions",
                        to="talks.talks",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
