# Generated by Django 5.2.5 on 2026-02-23 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkReviewComment",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment on talk.")),
                (
                    "talk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_review_comments",
                        to="talks.talks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talk Review Comment",
                "verbose_name_plural": "Talk Review Comments",
            },
        ),
    ]
