# Generated by Django 5.2.5 on 2025-09-07 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talks",
            name="presentation_files",
            field=models.FileField(null=True, upload_to="presentation_files"),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        help_text="session type. eg. Keynote, lightning talk. etc",
                        max_length=255,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(help_text="session duration in minutes"),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_sessions",
                        to="talks.talks",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
