# Generated by Django 5.2.5 on 2026-02-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When True, the talk proposal is visible for review by others'),
        ),
    ]
