# Generated by Django 5.2.5 on 2026-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0002_talks_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="talks",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="talks",
            name="event",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
