# Generated by Django 5.2.5 on 2026-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talkreviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talkreviewcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
