# Generated by Django 5.2.5 on 2025-09-27 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_delete_session"),
        ("talks", "0002_talks_presentation_files_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="talks",
            name="event",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talk_event",
                to="events.event",
            ),
            preserve_default=False,
        ),
    ]
