# Generated by Django 5.2.5 on 2026-02-28 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0003_alter_session_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkreviewcomment",
            name="rating",
            field=models.IntegerField(
                default=5,
                help_text="Rating from 1 to 5.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="talks",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="talks",
            name="is_reviewable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="talks",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
