# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_alter_talkreviewcomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
