# Generated by Django 5.2.5 on 2026-10-03 20:50

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0007_alter_talks_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talks",
            name="presentation_files",
            field=models.FileField(
                null=True,
                upload_to="presentation_files",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "ppt",
                            "pptx",
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                        ]
                    ),
                    base.validators.validate_presentation_size,
                ],
            ),
        ),
    ]
