# Generated by Django 5.2.5 on 2025-11-17 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("username", models.CharField(max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_given_feedback", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AttendeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notification_preference",
                    models.CharField(max_length=255, null=True),
                ),
                ("organization", models.CharField(max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendeeSocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255, null=True)),
                ("link", models.URLField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
