# Generated by Django 5.2.5 on 2025-08-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendeeprofile",
            old_name="user",
            new_name="user_account",
        ),
    ]
