# Generated by Django 5.2.5 on 2025-11-17 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendees", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeprofile",
            name="user_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_profile_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendees.attendeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="attendeesociallinks",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="attendees.attendeeprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("attendee", "event")},
        ),
    ]
