# Generated by Django 5.2.5 on 2025-09-09 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0002_rename_user_attendeeprofile_user_account"),
        ("events", "0002_delete_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("username", models.CharField(max_length=255, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_given_feedback", models.BooleanField(default=False)),
                (
                    "attendee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendees.attendeeprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("attendee", "event")},
            },
        ),
    ]
