# Generated by Django 5.2.5 on 2025-11-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0003_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendance",
                to="events.event",
            ),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="attendee",
        ),
    ]
