# Generated by Django 5.2.5 on 2025-10-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0003_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendeeprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="attendeeprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="attendeeprofile",
            name="last_name",
        ),
    ]
