# Generated by Django 5.2.5 on 2025-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendees", "0004_alter_attendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeesociallinks",
            name="link",
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="attendeesociallinks",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
