# Generated by Django 5.2.5 on 2026-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_alter_attendeesociallinks_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendeesociallinks',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendeesociallinks',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendeesociallinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
