# Generated by Django 5.2.5 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_convert_ids_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
