name: Integration Tests

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**/*.md'

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: speakwise_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12.0']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install psycopg2

      - name: Verify Postgres Connection
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d speakwise_test -c '\l'

      - name: Run DB Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/speakwise_test
        run: |
          python manage.py migrate --noinput
