name: Integration Tests

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**/*.md'

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: speakwise_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12.0']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          pip install -r requirements.txt
          pip install psycopg2-binary

      - name: Run DB Migrations
        working-directory: .
        env:
          DJANGO_SETTINGS_MODULE: speakwise.settings.local
          ENGINE: django.db.backends.postgresql,
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
          DJANGO_DB_NAME: speakwise_test
          DJANGO_DB_USER: postgres
          DJANGO_DB_PASSWORD: postgres
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python manage.py migrate --noinput