name: Run precommit

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['main', 'development']
    paths-ignore: ['docs/**']

  push:
    branches: ['main', 'development']
    paths-ignore: ['docs/**']

  workflow_call:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit dependencies
        run: pip install pre-commit

      - name: Run pre-commit
        working-directory: .
        run: pre-commit run --all-files
